name: Create Branch

on:
  workflow_dispatch:
    inputs:
      BranchName:
        description: Enter the branch name
        required: true
        type: choice 
        options:
          - feature_cloudhub
          - development_cloudhub
          - integration_cloudhub
          - production_cloudhub
          - branch1
          - branch2
          - branch3
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - name: Branch Creation
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: ${{ github.event.inputs.BranchName }}
       

        

 
         
