name: Create Branch

on:
  workflow_dispatch:
    inputs:
      BranchName:
        description: Enter the branch name
        required: true
        type: choice 
        options:
          - feature_cloudhub
          - development_cloudhub
          - integration_cloudhub
          - production_cloudhub
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       

        

 
         
