name: Create Branch

on:
 workflow_dispatch:
    inputs:
      BranchName:
      type: choice 
      description: Enter the branch name
      required: true
      options:
       - feature_cloudhub
       - development_cloudhub
       - integration_cloudhub
       - production_cloudhub


 
         
