name: Create Branch

on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
    
   workflow_dispatch:
    inputs:
      BranchName:
      type: choice 
      description: Enter the branch name
      required: true
      options:
       - feature_cloudhub
       - development_cloudhub
       - integration_cloudhub
       - production_cloudhub
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - name: Branch Creation
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.BRANCH_TOKEN }}
        with:
          branch: 

 
         
