name: Create Branch

on:
  workflow_dispatch:
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - name: Branch Creation
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.BRANCH_TOKEN }}
        with:
          branch: 'Testing'

 
         
